# Generano datos Aleatorio

In [2]:
import numpy as np

# Arrange

In [3]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Zeros

In [4]:

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Ones

In [5]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Eye

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Linspace

In [8]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# Radom

In [9]:
np.random.rand()

0.673904993101624

In [10]:
np.random.rand(4)

array([0.40612151, 0.05850057, 0.87912454, 0.96212241])

In [11]:
np.random.rand(4,4)

array([[0.83507858, 0.3740006 , 0.10164234, 0.29295593],
       [0.50623944, 0.38274896, 0.75163354, 0.96158161],
       [0.91620902, 0.91667901, 0.24256893, 0.99062965],
       [0.57285633, 0.74902327, 0.83022446, 0.52964207]])

In [12]:
np.random.randint(1,100,(10,10))

array([[82,  9, 90, 68, 43, 70, 60, 64, 51, 32],
       [58, 77, 54, 48, 17, 23, 12, 51, 81, 90],
       [23, 43, 95, 38, 70,  5, 13,  3, 88, 34],
       [47, 27, 78, 53,  9, 18, 84, 77, 39,  5],
       [ 2, 72, 71, 71,  2, 46, 82, 85, 84, 25],
       [30, 26, 81, 33, 32, 12, 48, 23, 12, 53],
       [33, 65, 89, 76, 67, 82, 82,  1, 95, 40],
       [81, 18, 65, 92, 69, 53, 15, 36, 54, 45],
       [38, 62, 55, 88, 54, 23, 51,  1, 43, 47],
       [11, 12, 53, 82, 79, 33, 79, 73, 86, 98]])